# Generated by Django 5.2.14 on 2026-05-15 15:46

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credito',
            name='comentarios_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='estado',
            field=models.CharField(default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='credito',
            name='numero_credito',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credito',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.ruta_carpeta_alumno),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
