# Generated by Django 5.2.14 on 2026-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_credito_alumno_credito_comentarios_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='numero_credito',
            field=models.IntegerField(default=1),
        ),
    ]
