# Generated by Django 5.2.14 on 2026-05-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_credito_numero_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='link_drive',
            field=models.URLField(blank=True, null=True),
        ),
    ]
