# Generated by Django 5.2.14 on 2026-05-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_credito_link_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='numero_constancia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='tipo',
            field=models.CharField(choices=[('credito', 'Crédito Único'), ('constancia', 'Constancia')], default='credito', max_length=20),
        ),
    ]
